### ISSUE TITLE
Koodikatselmointi #1

### ISSUE THREAD

**Issue by otahontas** [mjjs/gompressor#1]
# Koodikatselmointi

Arvioitu commit: https://github.com/mjjs/gompressor/commit/f915d17f7e5d5cb494f7f83215748b73c2812c46

Ladattu 29.11.2020. Pahoittelen, katselmointi tulee hieman myöhässä!

**Mitä tein**
- Latasin projektin ja asensin sen
- Ajoin testit ja suorituskykytestit
- Ajoin ohjelman valmiita testitiedostoja sekä paria muuta tiedostotyyppiä (musiikkia ja videota) vastaan

**Huomioita ohjelman toiminnallisuudesta**:
- Ohjelman TUI on selkeä, eikä sekoita päätä. Ehkäpä silti simppeli CLI flageilla voisi toimia paremmin tähän tarkoitukseen? TUI ei myöskää reagoinut exit-signaaliin `CTRL-C`, vaan oli täysin blokattuna, kun suoritti.
- Esimerkkisyötteillä ohjelma pyöri kuten odotettua, eikä tietoa kadonnut, hyvä!
- LZW:llä ohjelma meni tukkoon melko pienelläkin mp3-syötteellä (8.5 megaa), huffman suoriutui hommasta mallikkaasti, eikä kadottanut tietoa. Ehkä lzw-toteutuksessasi on suurempien inputtien käsittelyssä jotain hassua?
- Ajoin ohjelmaa yhtä aika isoa tiedostoa (50 megaa) vasten lzw:llä ja kesto oli melkoinen. Dokkareissa voisi olla tietysti jokin maininta siitä, mikä on suunnilleen ohjelman inputtien maksimi (sellainen, jonka pystyy säädyllisessä ajassa käsittelemään).

**Huomioita koodista ja koodityylistä**:
- Koodi on suhteellisen hyvin luettavaa ja ymmärrettävää. Joiltain osin olisin toivonut enemmän funktioiden dokumentointia: esimerkiksi huffmanin toteuttavassa koodissa lukemiskokemus oli aika lailla funktiota funktion perään. En toki ole kauhean sinut go-puolen dokumentointikäytänteiden kanssa, mutta myös "privaattifunktioiden" dokuementointi helpottaisi lukemista.
- Jos go:ssa on jotain abstrahointimahdollisuuksia, niin toteuttaisin jonkin rajapinta-tyyppisen ratkaisun, jonka huffman ja lzw voisivat implementoida. Kummankin algoritmin toiminnallisuus ulospäin on kuitenkin aika lailla samaa.

**Huomioita muusta**:
- README:hen voisi lisätä pikakäyttöohjeet, kuten monessa projektissa on tapana: "aja `go install` asentaaksesi ohjelman, xxyy generoidaksesi kattavuuden" jne. On vain mukavampi nähdä yhdellä vilkaisulla nopeasti kaikki, mitä tarvitaan tämän projektin devausympäristön setuppaamiseen.
- Testaamiseen voisi olla vain yksi tapa, joka myös generoisi koodikattavuuden?
- Godocit onlinessa eivät toimi, saan kaikista directoryistä "Not Found"

**Comment by mjjs** [comment]
Hyviä huomioita. Tässä muutama vastaus niihin (en odota näihin enää mitään vastausta).

* Ohjelma toimi alunperin flageilla, mutta toteutin siihen kevyen TUI:n, koska en ollut varma riittävätkö flagit kurssin edellyttämään käyttöliittymään.
* Olen huomannut LZW:n toteutuksesani saman hitauden. Mikäli aikaa jää, yritän optimoida sen toimimaan nopeammin.
* Muutin projektin rakennetta viikonloppuna, eikä Godoc ole päivittynyt (tarvitsee uuden releasen repositoryyn päivittyäkseen). Kiitos huomautuksesta.
* En ole toteuttanut mitään rajapintaa näille algoritmeille, koska mielestäni näin pienessä projektissa se vain monimutkaistaisi asioita.
* Huffman koodini vaatii tosiaan vielä selkeyttämistä (refaktorointi/dokumentointi).
